### ISSUE TITLE
IF I want to  test a new picture, how should I prepocess a new picture?

### ISSUE THREAD

**Issue by zss977-web** [gicheonkang/gst-visdial#1]
Hi, I am reading your paper about Visdial Dialog ,and do my own job, this work has helped me a lot. I want to test a new picture which is not in the dataset with a light method, and I realize that I don't know how to get the feature with a shape[36,2048].  I try to use torchvision which contiain the pre-trained Faster R-CNN model, but I don't know which layer of Faster R-CNN net should be set as Output during model.predict().  Any advice or guidance will be huge helpful for me .
Tanks.

**Comment by gicheonkang** [comment]
Hi, thank you for your interest.

We extracted faster r-cnn features by referring to the [lxmert](https://github.com/airsplay/lxmert) and [vilbert](https://github.com/jiasenlu/vilbert_beta/tree/master/data) repositories. The lxmert work provides a docker file to extract faster r-cnn features.

1.  After accessing the docker container, you should customize /opt/butd/tools/generate_tsv.py file to extract features. Please modify the file based on [this](https://github.com/jiasenlu/bottom-up-attention/blob/master/tools/generate_tsv.py).
2. You can get a tsv file. Try to convert it to lmdb file by checking [this file](https://github.com/gicheonkang/gst-visdial/blob/master/preprocessing/convert_to_lmdb.py).

Hope this will help you to extract features!

**Comment by zss977-web** [comment]
Very appreciate，that will help me a lot !

**Comment by gicheonkang** [comment]
If you have a further question, please reopen this issue. Thanks!
