### ISSUE TITLE
About the train_processed.json

### ISSUE THREAD

**Issue by DericZhao** [gicheonkang/gst-visdial#7]
Dear Gi-Cheon Kang,

I downloaded the dataset from the official website, but I found that the JSON files are all numbers. 

May I ask if a vocabulary is provided in the dataset? Or is there any function that can convert the number into the word?

I would greatly appreciate your help!

**Comment by gicheonkang** [comment]
Hi, Thank you for your interest!

As you can see in the [preprocessing code](https://github.com/gicheonkang/gst-visdial/tree/master/preprocessing/pre_process_visdial_v1.0.py), we tokenized and encoded the original visual dialog dataset (i.e., train.json in the [official VisDial dataset](https://visualdialog.org/data)) into BertTokenizer, which results in the train_processed.json file.

If you want to see the word, please check the original train file (train.json) or decode the numbers into words using BertTokenizer.

Hope this helps!

**Comment by gicheonkang** [comment]
If you have further questions, please reopen this issue. Thanks!
